### ISSUE TITLE
fix/improve logging

### ISSUE THREAD

**Issue by seansfkelley** [asini/asini#40]
I found a couple issues in Lerna which I think you have inherited that are pretty bad to have lying around. Just bringing these to your attention:
- https://github.com/lerna/lerna/pull/372
- https://github.com/lerna/lerna/pull/373

**Comment by gigabo** [comment]
Thanks for pointing those out @seansfkelley!

We've actually already addressed the the `logify*` breakage in https://github.com/asini/asini/pull/6, but it looks like we didn't catch the [sync/async typo](https://github.com/lerna/lerna/pull/372/files#diff-5463599b8d45d087bae97f0d5df54fdaL37) around `execInDir`.

The second one is a little tough for me to mentally pick apart from the first, since the diff shows the union of both change sets.  Looks like the meat of it is the accumulation of stdout in `spawn` so it can be emitted on error?  Makes sense, though I wonder about the memory use implications...

**Comment by seansfkelley** [comment]
Re: the second one, yes.

Edit: oops, got myself confused. This refers to the logify fixes:

> I had to truncate the argument lists to 100 characters to keep it form OOMing, which is a pretty inelegant solution. I'm open to other ideas. Looks like you hit the same issue in #6 though.

As for holding onto all of stdout, yeah, I don't yet have a good answer for that. A lot of my errors come through stdout though (various tools I use do this) so it was a must in one form or another.

**Comment by gigabo** [comment]
Yeah, useful error output should be worth the memory cost.

For the test OOMs we just [disabled log accumulation](https://github.com/asini/asini/pull/7) during tests.  A better solution may have been to flush logs after successful completion of a command.  Really only an issue during tests, though, since they run many commands in a single process.
