### ISSUE TITLE
Drop node v0.10 support?

### ISSUE THREAD

**Issue by gigabo** [asini/asini#61]
Node v0.10 has reached "end of life".

https://twitter.com/nodejs/status/793524310979833857
> Node.js v0.10 reached its "end of life" yesterday.

Asini still supports it, but it is [causing headaches](https://github.com/asini/asini/pull/58#issuecomment-261614264) for contributors.

Is anyone still using node v0.10?  Can we drop support?

**Comment by evocateur** [comment]
Looking into some of the many "out of date" dependencies, several are blocked from updating because they lack v0.10 compatibility:

## `dependencies`
- [inquirer](https://github.com/SBoudrias/Inquirer.js/releases/tag/v1.0.0) (needs native `Promise`, which could be polyfilled)

## `devDependencies`
- [cross-env](https://github.com/kentcdodds/cross-env/releases/tag/v3.0.0) (needs native `Object.assign`)
- [fs-extra](https://github.com/jprichardson/node-fs-extra/blob/1.x/CHANGELOG.md#100--2016-11-01) 

It's not the end of the world, certainly, but it is notable. (node v4+ is the next major hiccup in terms of the rest of the outdated dependencies)

**Comment by gigabo** [comment]
Nice, thanks for the research @evocateur.  Looks like the `inquirer` upgrade will need code changes in Asini to migrate to the new promise-based interface.  The others seems straightforward.

**Comment by evocateur** [comment]
#62 fixed this
